"""Mesh I/O: load and save OBJ, PLY, and OFF files."""
import numpy as np
from typing import Tuple
import re


def load_obj(filepath: str) -> Tuple[np.ndarray, np.ndarray]:
    """Load OBJ file. Returns (vertices, faces)."""
    vertices = []
    faces = []

    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            parts = line.split()
            if not parts:
                continue

            if parts[0] == 'v':
                # vertex
                v = [float(x) for x in parts[1:4]]
                vertices.append(v)
            elif parts[0] == 'f':
                # face (handles v, v/t, or v/t/n formats)
                face = []
                for part in parts[1:]:
                    # extract vertex index (first number before / or space)
                    # OBJ uses -1-indexing
                    idx = int(part.split('/')[0])
                    if idx < 0:
                        v_idx = len(vertices) + idx
                    else:
                        v_idx = idx - 1
                    face.append(v_idx)

                if len(face) >= 3:
                    for i in range(1, len(face) - 1):
                        faces.append([face[0], face[i], face[i + 1]])
    V = np.array(vertices, dtype=float)
    F = np.array(faces, dtype=int)

    if np.any(F < 0) or np.any(F >= len(V)):
        raise ValueError("Face indices out of bounds")

    if np.isnan(V).any():
        raise ValueError("Mesh contains NaN vertices")

    return V, F


def save_obj(filepath: str, vertices: np.ndarray, faces: np.ndarray) -> None:
    """Save mesh to OBJ file."""
    with open(filepath, 'w') as f:
        f.write("# Generated by DDG\n")
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        for face in faces:
            f_str = " ".join(str(int(idx) + 1) for idx in face)
            f.write(f"f {f_str}\n")


def load_off(filepath: str) -> Tuple[np.ndarray, np.ndarray]:
    vertices = []
    faces = []

    with open(filepath, "r") as f:
        header = f.readline().strip()
        if header != "OFF":
            raise ValueError("Invalid OFF file (missing OFF header)")

        # Read counts (skip comments/empty lines)
        line = f.readline().strip()
        while not line or line.startswith("#"):
            line = f.readline().strip()

        parts = line.split()
        if len(parts) < 2:
            raise ValueError("OFF header malformed")

        n_verts = int(parts[0])
        n_faces = int(parts[1])

        # Read vertices
        for _ in range(n_verts):
            line = f.readline().strip()
            while not line:
                line = f.readline().strip()
            v = list(map(float, line.split()[:3]))
            vertices.append(v)

        # Read faces
        for _ in range(n_faces):
            line = f.readline().strip()
            while not line:
                line = f.readline().strip()
            parts = line.split()
            k = int(parts[0])
            indices = list(map(int, parts[1:k+1]))

            # triangulate if needed
            for i in range(1, len(indices) - 1):
                faces.append([indices[0], indices[i], indices[i+1]])
    V = np.array(vertices, dtype=float)
    F = np.array(faces, dtype=int)

    if np.any(F < 0) or np.any(F >= len(V)):
        raise ValueError("Face indices out of bounds")

    if np.isnan(V).any():
        raise ValueError("Mesh contains NaN vertices")

    return V, F

def save_off(filepath: str, vertices: np.ndarray, faces: np.ndarray) -> None:
    """Save mesh to OFF file."""
    with open(filepath, 'w') as f:
        f.write("OFF\n")
        f.write(f"{len(vertices)} {len(faces)} 0\n")
        for v in vertices:
            f.write(f"{v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        for face in faces:
            f.write(f"{len(face)} " + " ".join(str(int(idx)) for idx in face) + "\n")


def load_ply(filepath: str) -> Tuple[np.ndarray, np.ndarray]:
    vertices = []
    faces = []

    with open(filepath, 'r') as f:
        first_line = f.readline().strip()
        if first_line != "ply":
            raise ValueError("Not a valid PLY file")

        format_line = f.readline().strip()
        if "ascii" not in format_line:
            raise ValueError("Only ASCII PLY supported")

        n_verts = 0
        n_faces = 0

        # Parse header
        while True:
            line = f.readline().strip()
            if line.startswith("element vertex"):
                n_verts = int(line.split()[-1])
            elif line.startswith("element face"):
                n_faces = int(line.split()[-1])
            elif line == "end_header":
                break

        # Read vertices
        for _ in range(n_verts):
            parts = f.readline().strip().split()
            vertices.append(list(map(float, parts[:3])))

        # Read faces
        for _ in range(n_faces):
            parts = f.readline().strip().split()
            k = int(parts[0])
            indices = list(map(int, parts[1:k+1]))

            # triangulate
            for i in range(1, len(indices) - 1):
                faces.append([indices[0], indices[i], indices[i+1]])

    V = np.array(vertices, dtype=float)
    F = np.array(faces, dtype=int)

    if len(V) == 0 or len(F) == 0:
        raise ValueError("Loaded empty mesh")

    if np.any(F < 0) or np.any(F >= len(V)):
        raise ValueError("Face indices out of bounds")

    if np.isnan(V).any():
        raise ValueError("Mesh contains NaN vertices")

    return V, F

def save_ply(filepath: str, vertices: np.ndarray, faces: np.ndarray) -> None:
    """Save mesh to PLY file (ASCII format)."""
    with open(filepath, 'w') as f:
        f.write("ply\n")
        f.write("format ascii 1.0\n")
        f.write(f"element vertex {len(vertices)}\n")
        f.write("property float x\n")
        f.write("property float y\n")
        f.write("property float z\n")
        f.write(f"element face {len(faces)}\n")
        f.write("property list uchar int vertex_indices\n")
        f.write("end_header\n")

        for v in vertices:
            f.write(f"{v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")

        for face in faces:
            f.write(f"{len(face)} " + " ".join(str(int(idx)) for idx in face) + "\n")


def load_mesh(filepath: str) -> Tuple[np.ndarray, np.ndarray]:
    """Auto-load mesh from file (detects format from extension)."""
    ext = filepath.split('.')[-1].lower()

    if ext == 'obj':
        return load_obj(filepath)
    elif ext == 'off':
        return load_off(filepath)
    elif ext == 'ply':
        return load_ply(filepath)
    else:
        raise ValueError(f"Unsupported format: {ext}")


def save_mesh(filepath: str, vertices: np.ndarray, faces: np.ndarray) -> None:
    """Auto-save mesh to file (detects format from extension)."""
    ext = filepath.split('.')[-1].lower()

    if ext == 'obj':
        save_obj(filepath, vertices, faces)
    elif ext == 'off':
        save_off(filepath, vertices, faces)
    elif ext == 'ply':
        save_ply(filepath, vertices, faces)
    else:
        raise ValueError(f"Unsupported format: {ext}")


__all__ = [
    "load_obj", "save_obj",
    "load_off", "save_off",
    "load_ply", "save_ply",
    "load_mesh", "save_mesh",
]
